const ALIGNMENT = {
  COLUMN: "column",
  ROW: "row",
  CENTER: "center",
  LEFT: "left",
  RIGHT: "right",
  FLEXEND: "flex-end",
  FLEX_START: "flex-start",
  BASELINE: "baseline",
  STRETCH: "stretch",
  ALIGNAUTO: "auto",
  SPACE_AROUND: "space-around",
  SPACE_BETWEEN: "space-between",
  SPACE_EVENLY: "space-evenly",
  TOP: "top",
  CONTAIN: "contain",
  ABSOLUTE: "absolute",
  UNDERLINE: "underline",
};
export default ALIGNMENT;
