const TEXT = {
  HEADERTITLE: "Public experience",
  CREDENTIALTEXT: "Enter your credentials to sign in to your account",
  SIGNUPCREDENTIALTEXT: "Create your account and earn cashback",
  welcomeDescrioption: "Thank you for joining LuckyDiem",
  SIGNIN: "Sign In",
  SIGNUP: "Sign Up",
  VERIFY: "Verify",
  OTP_VERIFICATION: "OTP Verification",
  DID_RECEIVE_CODE: "Did't receive any code?",
  RE_SEND_CODE: "Re-send code",
  ENTER_FOUR_DIGIT_CODE: "Please Enter 4 digit code sent to johndoe2@gmail.com",
  NEWUSER: "New User? Join Now",
  SAVE: "SAVE",
  NEXT: "NEXT",
  GET_STARTED: "GET STARTED",
  PHONE: "",
  PHONE_NUMBER: "Phone Number",
  PASSWORD: "Password",
  LOGIN: "Login",
  MOBILE_NUM_FORMAT: "Email / Mobile",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  EMAIL: "Email",
  MOBILE: "Mobile (optional)",
  ZIPCODE: "Zip Code",
  WELCOME: "Welcome to LuckyDiem",
  CONTINUE_C: "hiii",
  EARN_CASE_TITLE: "Earn Cashback",
  LOYALTYLEBEL: "Loyalty Clubs",
  LOYALTYTITLE: "The higher the club, the bigger the rewards",
  BADGELEBEL: "Badges",
  MYPOSTLEBEL: "My Posts",
  LEADERLEBEL: "Leaderboards",
  REFFERALLEBEL: "Referral Programs",
  BADGETITLE: "Quick and easy way to earn Lucky Points",
  MYPOSTTITLE: "Create new ones and see your favorites",
  LEADERBOARDTITLE: "See how you stack up amongst all Lucky Users",
  REFFERALTITLE: "Earn $$$ on all of your referred friend" + "s" + "order",
  EARN_CASH:
    "When you link a card with LuckyDiem you can earn cash back at 1000s of our local merchants and online stores",
  WELCOME_TITLE:
    "Get started by linking your card. Every transaction is rewarding!",
  REFERRAL: "Referral Code (Optional)",
  LINK_CARD_TERMS_INFO1:
    "By checking this box and entering my card information," +
    " I agree to the following: I authorize my payment card network to monitor and share my transaction data made" +
    " with my registered payment card at participating merchants with LuckyDiem and its third-party service providers" +
    "(including Figg). LuckyDiem shall obtain, provide, and/ or use my transaction data to calculate my points," +
    " redeem rewards, enable card-linked offer(s), and to facilitate LuckyDiem in accordance with the ",
  LINK_CARD_TERMS_INFO2:
    " LuckyDiem may share my transaction data with participating merchants to determine if I am eligible to receive the offered reward. You may opt-out of" +
    "LuckyDiem at any time by visiting the 'linked Cards' page and deleting all of the cards linked.",
  LINK_CARD_AND: "and ",
  LINK_CARD_TERMS: "Program Terms of Use",
  LINK_CARD_PRIVACY: "Privacy Policy.",
  LINK_CARD_AGREE_TEXT: "Agree and Link Card",
  LINK_CARD_SKIP_TEXT: "Skip for now",
  LINK_CARD_ANOTHER: "Link Another Card",
  LINK_CARD_DONE: "I'm Done",
  CARD_LINKED: "Card Linked!",
  CARD_INSTRUCTION:
    "Use your linked card to pay at participating places for automatic cashback. Enjoy",
  CARD_NUMBER: "Card Number",
  CARD_HOLDER: "Card Holder",
  EXPIRES: "Expires",
  PROTIPS: "Pro Tips:",
  PROTIPS_INFO:
    "Add more eligible cards so you always earn cashback, no matter what card you use.",
  FEATURED: "Featured",
  LOCAL: "Local",
  ONLINE: "Online",
  RATINGS: "Ratings",
  DISTANCE: "Distance",
  CASHBACK: "Cashback",
  LUCKY_POINTS: "Lucky Points",
  OFFERS: "Offers",
  ORDER_FOOD: "Order Food",
  POSTS: "Posts",
  LEADERBOARD: "Leaderboard",
  ABOUT: "About",
  LOCATION_MESSAGE: "Please provide location access from Settings.",
  LOCATION_TITLE: "LuckyDiem",
  TITLE: "Lucky point",
  GPS_TEXT: "Use current location using GPS",
  SEARCH_LOCATION: "Search your location",
  MANAGECARDTITLE: "Manage Cards",
  MANAGEBANKACCOUNT: "Manage Bank Accounts",
  ACCOUNTSETTING: "Account Settings",
  STATEMENT: "My Statements",
  TOTALCASHBACK: "Total Cashback",
  THISMONTH: "This Month",
  ROOKIE: "ROOKIE",
  PRO: "PRO",
  VETERAN: "VETERAN",
  STAR: "STAR",
  MVP: "MVP",
  FRIEND: "Friends",
  CANCELFRIEND: "Cancel Request",
  ADD: "Add",
  SEARCH: "Search",
  SAVECHANGES: "Save Changes",
  ACCEPT: "Accept",
  PUBLISH_POST: "Publish Post",
  CONFIRM_SELECTIONS: "Confirm Selections",
  ALL_PHOTOS: "All Photos",
  UPTO_5_PHOTOS: "Up to 5 photos can be selected",
  PHOTO_VIDEO: "Photos/Videos",
  USE_CAMERA: "Use Camera",
  MAX_5: "5 Max",
  ADD_A_CAPTION: "Add a caption",
  RATE_EXPERIENCE: "Rate your Experience (optional)",
  SELECT_LOCATION: "Select Location",
  VIEW_DETAILS: "View details",
  POLL_OF_DAY: "POLL OF THE DAY",
  QUESTION: "What is your preferred method of\nfood consumption?",
  LIKES: "Likes",
  SHARE: "Share",
  LP_EARNED: "LP Earned",
  REFERRAL_PROMO_CODE: "Referral Promo Code",
  MANAGE_ADDRESS: "Manage Address",
  VISIBILITY_SETTINGS: "Visibility Settings",
  NOTIFICATION_SETTINGS: "Notification Settings",
  CHANGE_PASSWORD: "Change Password",
  FAQ: "FAQ",
  CONTACT_US: "Contact Us",
  LOGOUT_TEXT: "Logout",
  // TExt added by Simran
  EMPTY_MERCHANT_POST: "It seems there are no shared posts.",
  WIN_GOLD_RAFFLE: "Win a Gold Raffle!",
  WIN_GOLD_RAFFLE_HEADING:
    "Be the first to create a post and get a\nchance to win a Gold Raffle.",
  CREATE_FIRST_POST: "Create your first post and",
  MEDIA_OPTIONS: "What would you like pick from Photo Gallery",
  PROFILE_UPDATED_SUCCESS: "Profile Updated successfully",
  LOGOUT: "Are you sure want to logout?",
  MERCHANTS: 'Merchants',
  PROFILES: 'Profiles',
  NO_MERCHANT_FOUND: 'No Merchant Found!',
  NO_PROFILE_FOUND: 'No Profile Found!',
  NO_MERCHANT_FOUND_DESC: 'We couldn’t found any merchant for that search.',
  NO_PROFILE_FOUND_DESC: 'We couldn’t found any profile for that search.',
  RECENT_SEARCHES: 'Recent Searches',
  TOP_CUISINES: 'Top Cuisines',
  BUSINESS_NEARBY: 'Businesses Nearby',
  YOUR_FAVOURITES: 'Your Favourites',
  /************************ */
};
export default TEXT;
